/*
 * StatusWordBits.hpp
 *
 *  Created on: Apr 20, 2012
 *      Author: hdpc
 */

#define STATUSWORD_READY_TO_SWITCH_ON_BIT 0
#define STATUSWORD_SWITCHED_ON_BIT 1
#define STATUSWORD_OPERATION_ENABLE_BIT 2
#define STATUSWORD_FAULT_BIT 3
#define STATUSWORD_VOLTAGE_ENABLE_BIT 4
#define STATUSWORD_QUICK_STOP_BIT 5
#define STATUSWORD_SWITCH_ON_DISABLE_BIT 6
#define STATUSWORD_NO_USED_WARNING_BIT 7
#define STATUSWORD_ELMO_NOT_USED_BIT 8
#define STATUSWORD_REMOTE_BIT 9
#define STATUSWORD_TARGET_REACHED_BIT 10
#define STATUSWORD_INTERNAL_LIMIT_ACTIVE_BIT 11


